## Importing Data

In [1]:
from pycaret.datasets import get_data

In [2]:
data=get_data('insurance')

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
from pycaret.regression import *

In [4]:
s = setup(data,target='charges',session_id=123)

Setup Succesfully Completed!